version: "2"

services:
  authapp:
    build:
      context: .
      dockerfile: authapp/Dockerfile
      args:
        AUTHAPP_SVC_NAME: authapp
        AUTHAPP_SVC_PORT: 3000
    ports:
      - 3000:3000
    restart: always
  fetchapp:
    build:
      context: .
      dockerfile: fetchapp/Dockerfile
      args:
        FETCHAPP_SVC_NAME: fetchapp
        FETCHAPP_SVC_PORT: 8000
    ports:
      - 8000:8000
    restart: always
